In [1]:
import numpy as np

array1d

In [2]:
x1d = np.array([1,2,3,4,5])
print(x1d)

[1 2 3 4 5]


array2d

In [3]:
x2d = np.array([ [1,2,3,4,5],
                 [6,8,11,3,9],
                 [8,6,5,3,1]
                ])
print(x2d)

[[ 1  2  3  4  5]
 [ 6  8 11  3  9]
 [ 8  6  5  3  1]]


---

arange : สร้างค่าจาก  start ไปจนถึง stop

In [4]:
a = np.arange(start=3, stop=11, step=1)
print(a)

[ 3  4  5  6  7  8  9 10]


In [64]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

---

Reshape : แปลง array จากขนาดนึงไปอีกอันนึง โดยขนาดใหม่ที่ต้องการแปลงต้องมีขนาดรวม = จำนวนข้อมูล

In [5]:
np.arange(start=1,stop=17,step=1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [6]:
np.arange(start=1,stop=17,step=1).reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [7]:
np.arange(start=1,stop=17,step=1).reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [8]:
np.arange(start=1,stop=17,step=1).reshape(8,1) # ที่ไม่ได้เพราะว่า "ขนาดใหม่ที่ต้องการมีค่าไม่เท่ากับจำนวนข้อมูล"

ValueError: cannot reshape array of size 16 into shape (8,1)

---

- np.ones = ประกาส array ที่มีค่า = 1 โดยมีขนาด = shape ที่ใส่ลงไป
- np.zeros = ประกาส array ที่มีค่า = 0 โดยมีขนาด = shape ที่ใส่ลงไป
- np.shape = เอาไว้เช็คขนาดของ array 

In [9]:
k = np.ones(10)
print(k)
print(f"shape = {k.shape}")

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
shape = (10,)


In [10]:
h = np.zeros(10)
print(h)
print(f"shape = {h.shape}")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
shape = (10,)


In [11]:
k2 = np.ones((5,5))
print(k2)
print(f"shape = {k2.shape}")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
shape = (5, 5)


In [12]:
h2 = np.zeros((4,3))
print(h2)
print(f"shape = {h2.shape}")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
shape = (4, 3)


In [13]:
k3 = np.ones((2,3,6))
print(k3)
print(f"shape = {k3.shape}")

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
shape = (2, 3, 6)


---

Index & Slicing

In [38]:
a = np.arange(start=0,stop=10,step=1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a[:8] #เอาตั้งแต่ index 0 ไปถึง index ที่ 8-1 

array([0, 1, 2, 3, 4, 5, 6, 7])

In [53]:
a[1:5] #เอา index ที่ 1 ไปถึง index ที่ 5-1

array([1, 2, 3, 4])

In [54]:
a[3:] #เอา index ที่ 3 ไปถึง index ที่ n

array([3, 4, 5, 6, 7, 8, 9])

In [55]:
a[:-3] #เอา index ที่ 0 ไปถึง index ที่ n-3 (ตัด3ตัวท้ายออก)

array([0, 1, 2, 3, 4, 5, 6])

In [51]:
a[-4:] #เอา index ที่ n-4 ไปถึง n (เอา 4 ตัวท้าย)

array([6, 7, 8, 9])

In [56]:
a[2:-2] #เอา index ที่ 2 ไปถึง index ที่ n-2 (เริ่มที่ 2 ไปจนจบ แต่ไม่เอา 2 ตัวท้าย)

array([2, 3, 4, 5, 6, 7])